In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('../../Data/Pharmacy/D1.csv')

In [3]:
df.head()

,saleinvcode,CustomerRef,date,invdiscperc,flatdisc,misccharges,invsalestax,remarks,looseqty,packqty,price,itemdiscperc,packunits,batch,expiry,salestax,itemname,datestring,customer,rowid
0,115439,NaN,7/1/22 0:02,0.0,0.0,0,0,NaN,1,0,18.00,0.0,1,.,7/5/24 0:00,0,PEDITRAL (LEMON) ORS SACHET,1/7/2022,****CASH SALES CUSTOMER,226819
1,115440,NaN,7/1/22 0:03,0.0,3.0,0,0,NaN,3,0,6.31,0.0,20,.,2/8/24 0:00,0,SPIROMIDE 20MG TAB,1/7/2022,****CASH SALES CUSTOMER,226820
2,115440,NaN,7/1/22 0:03,0.0,3.0,0,0,NaN,2,0,7.83,0.0,30,.,8/1/25 0:00,0,CARLOV 6.25MG TAB(30'S),1/7/2022,****CASH SALES CUSTOMER,226821
3,115440,NaN,7/1/22 0:03,0.0,3.0,0,0,NaN,2,0,34.29,0.0,14,.,10/1/24 0:00,0,NEXUM 40MG CAP,1/7/2022,****CASH SALES CUSTOMER,226822
4,115441,NaN,7/1/22 0:04,0.0,0.0,0,0,NaN,8,0,6.31,0.0,20,.,2/8/24 0:00,0,SPIROMIDE 20MG TAB,1/7/2022,****CASH SALES CUSTOMER,226823

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348048 entries, 0 to 348047
Data columns (total 20 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   saleinvcode   348048 non-null  int64
 1   CustomerRef   590 non-null     object
 2   date          348048 non-null  object
 3   invdiscperc   348048 non-null  float64
 4   flatdisc      348048 non-null  float64
 5   misccharges   348048 non-null  int64
 6   invsalestax   348048 non-null  int64
 7   remarks       76429 non-null   object
 8   looseqty      348048 non-null  int64
 9   packqty       348048 non-null  int64
 10  price         348048 non-null  float64
 11  itemdiscperc  348048 non-null  float64
 12  packunits     348048 non-null  int64
 13  batch         348048 non-null  object
 14  expiry        348048 non-null  object
 15  salestax      348048 non-null  int64
 16  itemname      348048 non-null  object
 17  datestring    348048 non-null  object
 18  customer      348048 non-null  object
 19  rowid         348048 non-null  int64
dtypes: float64(4), int64(8), object(8)
memory usage: 53.1+ MB

In [5]:
corr_matrix = df.corr(numeric_only=True)

In [6]:
print(corr_matrix)

              saleinvcode  invdiscperc  flatdisc  misccharges  invsalestax  \
saleinvcode      1.000000     0.006366  0.001077          NaN          NaN
invdiscperc      0.006366     1.000000  0.091591          NaN          NaN
flatdisc         0.001077     0.091591  1.000000          NaN          NaN
misccharges           NaN          NaN       NaN          NaN          NaN
invsalestax           NaN          NaN       NaN          NaN          NaN
looseqty         0.006968     0.116450  0.028431          NaN          NaN
packqty               NaN          NaN       NaN          NaN          NaN
price            0.023050    -0.084360 -0.052529          NaN          NaN
itemdiscperc    -0.020194    -0.164554 -0.090229          NaN          NaN
packunits       -0.019841    -0.070127 -0.031087          NaN          NaN
salestax              NaN          NaN       NaN          NaN          NaN
rowid            0.999981     0.006275  0.001189          NaN          NaN

              looseqty  packqty     price  itemdiscperc  packunits  salestax  \
saleinvcode   0.006968      NaN  0.023050     -0.020194  -0.019841       NaN
invdiscperc   0.116450      NaN -0.084360     -0.164554  -0.070127       NaN
flatdisc      0.028431      NaN -0.052529     -0.090229  -0.031087       NaN
misccharges        NaN      NaN       NaN           NaN        NaN       NaN
invsalestax        NaN      NaN       NaN           NaN        NaN       NaN
looseqty      1.000000      NaN -0.140057      0.104406   0.140369       NaN
packqty            NaN      NaN       NaN           NaN        NaN       NaN
price        -0.140057      NaN  1.000000     -0.027276  -0.137714       NaN
itemdiscperc  0.104406      NaN -0.027276      1.000000  -0.053367       NaN
packunits     0.140369      NaN -0.137714     -0.053367   1.000000       NaN
salestax           NaN      NaN       NaN           NaN        NaN       NaN
rowid         0.006960      NaN  0.023025     -0.020132  -0.019878       NaN

                 rowid
saleinvcode   0.999981
invdiscperc   0.006275
flatdisc      0.001189
misccharges        NaN
invsalestax        NaN
looseqty      0.006960
packqty            NaN
price         0.023025
itemdiscperc -0.020132
packunits    -0.019878
salestax           NaN
rowid         1.000000

In [7]:
columns_to_drop = ['saleinvcode', 'CustomerRef', 'invdiscperc', 'flatdisc', 'misccharges', 'invsalestax', 'remarks', 'packqty', 'itemdiscperc', 'batch', 'salestax', 'customer', 'rowid']
df = df.drop(columns=columns_to_drop, axis=1)

In [8]:
df.head()

,date,looseqty,price,packunits,expiry,itemname,datestring
0,7/1/22 0:02,1,18.00,1,7/5/24 0:00,PEDITRAL (LEMON) ORS SACHET,1/7/2022
1,7/1/22 0:03,3,6.31,20,2/8/24 0:00,SPIROMIDE 20MG TAB,1/7/2022
2,7/1/22 0:03,2,7.83,30,8/1/25 0:00,CARLOV 6.25MG TAB(30'S),1/7/2022
3,7/1/22 0:03,2,34.29,14,10/1/24 0:00,NEXUM 40MG CAP,1/7/2022
4,7/1/22 0:04,8,6.31,20,2/8/24 0:00,SPIROMIDE 20MG TAB,1/7/2022

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348048 entries, 0 to 348047
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        348048 non-null  object
 1   looseqty    348048 non-null  int64
 2   price       348048 non-null  float64
 3   packunits   348048 non-null  int64
 4   expiry      348048 non-null  object
 5   itemname    348048 non-null  object
 6   datestring  348048 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 18.6+ MB

In [10]:
df.to_csv('../../Data/Pharmacy/D2.csv', index=False)