In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error

In [2]:
train = pd.read_csv("../../Data/Kaggle/StoreSales/new_train.csv")
test = pd.read_csv("../../Data/Kaggle/StoreSales/new_test.csv")

In [3]:
train.head()

,date,store_nbr,family,sales,onpromotion,typeholiday,dcoilwtico,city,state,typestores,cluster,day_of_week,month,year
0,2013-01-01,1,AUTOMOTIVE,0.0,0,Holiday,93.14,Quito,Pichincha,D,13,2,1,2013
1,2013-01-01,1,BABY CARE,0.0,0,Holiday,93.14,Quito,Pichincha,D,13,2,1,2013
2,2013-01-01,1,BEAUTY,0.0,0,Holiday,93.14,Quito,Pichincha,D,13,2,1,2013
3,2013-01-01,1,BEVERAGES,0.0,0,Holiday,93.14,Quito,Pichincha,D,13,2,1,2013
4,2013-01-01,1,BOOKS,0.0,0,Holiday,93.14,Quito,Pichincha,D,13,2,1,2013

In [4]:
X = train.drop(['sales'], axis=1)
y = train['sales']

In [5]:
X = pd.get_dummies(X)

In [6]:
X.shape

(3000888, 1773)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
batch_size = 10000

In [9]:
num_batches = len(X_train) // batch_size + 1

In [10]:
model = XGBRegressor(objective='reg:squarederror', n_estimators=100, random_state=42)

In [11]:
for i in range(num_batches):
    start_idx = i * batch_size
    end_idx = (i + 1) * batch_size

    X_batch = X_train.iloc[start_idx:end_idx]
    y_batch = y_train.iloc[start_idx:end_idx]

    model.fit(X_batch, y_batch)

    print(f"Batch {i + 1}/{num_batches} completed")

Batch 1/241 completed
Batch 2/241 completed
Batch 3/241 completed
Batch 4/241 completed
Batch 5/241 completed
Batch 6/241 completed
Batch 7/241 completed
Batch 8/241 completed
Batch 9/241 completed
Batch 10/241 completed
Batch 11/241 completed
Batch 12/241 completed
Batch 13/241 completed
Batch 14/241 completed
Batch 15/241 completed
Batch 16/241 completed
Batch 17/241 completed
Batch 18/241 completed
Batch 19/241 completed
Batch 20/241 completed
Batch 21/241 completed
Batch 22/241 completed
Batch 23/241 completed
Batch 24/241 completed
Batch 25/241 completed
Batch 26/241 completed
Batch 27/241 completed
Batch 28/241 completed
Batch 29/241 completed
Batch 30/241 completed
Batch 31/241 completed
Batch 32/241 completed
Batch 33/241 completed
Batch 34/241 completed
Batch 35/241 completed
Batch 36/241 completed
Batch 37/241 completed
Batch 38/241 completed
Batch 39/241 completed
Batch 40/241 completed
Batch 41/241 completed
Batch 42/241 completed
Batch 43/241 completed
Batch 44/241 completed
Batch 45/241 completed
Batch 46/241 completed
Batch 47/241 completed
Batch 48/241 completed
Batch 49/241 completed
Batch 50/241 completed
Batch 51/241 completed
Batch 52/241 completed
Batch 53/241 completed
Batch 54/241 completed
Batch 55/241 completed
Batch 56/241 completed
Batch 57/241 completed
Batch 58/241 completed
Batch 59/241 completed
Batch 60/241 completed
Batch 61/241 completed
Batch 62/241 completed
Batch 63/241 completed
Batch 64/241 completed
Batch 65/241 completed
Batch 66/241 completed
Batch 67/241 completed
Batch 68/241 completed
Batch 69/241 completed
Batch 70/241 completed
Batch 71/241 completed
Batch 72/241 completed
Batch 73/241 completed
Batch 74/241 completed
Batch 75/241 completed
Batch 76/241 completed
Batch 77/241 completed
Batch 78/241 completed
Batch 79/241 completed
Batch 80/241 completed
Batch 81/241 completed
Batch 82/241 completed
Batch 83/241 completed
Batch 84/241 completed
Batch 85/241 completed
Batch 86/241 completed
Batch 87/241 completed
Batch 88/241 completed
Batch 89/241 completed
Batch 90/241 completed
Batch 91/241 completed
Batch 92/241 completed
Batch 93/241 completed
Batch 94/241 completed
Batch 95/241 completed
Batch 96/241 completed
Batch 97/241 completed
Batch 98/241 completed
Batch 99/241 completed
Batch 100/241 completed
Batch 101/241 completed
Batch 102/241 completed
Batch 103/241 completed
Batch 104/241 completed
Batch 105/241 completed
Batch 106/241 completed
Batch 107/241 completed
Batch 108/241 completed
Batch 109/241 completed
Batch 110/241 completed
Batch 111/241 completed
Batch 112/241 completed
Batch 113/241 completed
Batch 114/241 completed
Batch 115/241 completed
Batch 116/241 completed
Batch 117/241 completed
Batch 118/241 completed
Batch 119/241 completed
Batch 120/241 completed
Batch 121/241 completed
Batch 122/241 completed
Batch 123/241 completed
Batch 124/241 completed
Batch 125/241 completed
Batch 126/241 completed
Batch 127/241 completed
Batch 128/241 completed
Batch 129/241 completed
Batch 130/241 completed
Batch 131/241 completed
Batch 132/241 completed
Batch 133/241 completed
Batch 134/241 completed
Batch 135/241 completed
Batch 136/241 completed
Batch 137/241 completed
Batch 138/241 completed
Batch 139/241 completed
Batch 140/241 completed
Batch 141/241 completed
Batch 142/241 completed
Batch 143/241 completed
Batch 144/241 completed
Batch 145/241 completed
Batch 146/241 completed
Batch 147/241 completed
Batch 148/241 completed
Batch 149/241 completed
Batch 150/241 completed
Batch 151/241 completed
Batch 152/241 completed
Batch 153/241 completed
Batch 154/241 completed
Batch 155/241 completed
Batch 156/241 completed
Batch 157/241 completed
Batch 158/241 completed
Batch 159/241 completed
Batch 160/241 completed
Batch 161/241 completed
Batch 162/241 completed
Batch 163/241 completed
Batch 164/241 completed
Batch 165/241 completed
Batch 166/241 completed
Batch 167/241 completed
Batch 168/241 completed
Batch 169/241 completed
Batch 170/241 completed
Batch 171/241 completed
Batch 172/241 completed
Batch 173/241 completed
Batch 174/241 completed
Batch 175/241 completed
Batch 176/241 completed
Batch 177/241 completed
Batch 178/241 completed
Batch 179/241 completed
Batch 180/241 completed
Batch 181/241 completed
Batch 182/241 completed
Batch 183/241 completed
Batch 184/241 completed
Batch 185/241 completed
Batch 186/241 completed
Batch 187/241 completed
Batch 188/241 completed
Batch 189/241 completed
Batch 190/241 completed
Batch 191/241 completed
Batch 192/241 completed
Batch 193/241 completed
Batch 194/241 completed
Batch 195/241 completed
Batch 196/241 completed
Batch 197/241 completed
Batch 198/241 completed
Batch 199/241 completed
Batch 200/241 completed
Batch 201/241 completed
Batch 202/241 completed
Batch 203/241 completed
Batch 204/241 completed
Batch 205/241 completed
Batch 206/241 completed
Batch 207/241 completed
Batch 208/241 completed
Batch 209/241 completed
Batch 210/241 completed
Batch 211/241 completed
Batch 212/241 completed
Batch 213/241 completed
Batch 214/241 completed
Batch 215/241 completed
Batch 216/241 completed
Batch 217/241 completed
Batch 218/241 completed
Batch 219/241 completed
Batch 220/241 completed
Batch 221/241 completed
Batch 222/241 completed
Batch 223/241 completed
Batch 224/241 completed
Batch 225/241 completed
Batch 226/241 completed
Batch 227/241 completed
Batch 228/241 completed
Batch 229/241 completed
Batch 230/241 completed
Batch 231/241 completed
Batch 232/241 completed
Batch 233/241 completed
Batch 234/241 completed
Batch 235/241 completed
Batch 236/241 completed
Batch 237/241 completed
Batch 238/241 completed
Batch 239/241 completed
Batch 240/241 completed
Batch 241/241 completed

In [12]:
y_pred = model.predict(X_test)

In [13]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

In [14]:
print(f'RMSE: {rmse}')

RMSE: 736.1971177716175